server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: cryptopal-core
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cryptopal}
    username: ${SPRING_DATASOURCE_USERNAME:cryptopal}
    password: ${SPRING_DATASOURCE_PASSWORD:change_me}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
